# This deployments have two replicas of the services
# This use protocol TCP and use port 6379
apiVersion: v1
kind: Service
metadata:
  name: replica
spec:
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    name: redis
  selector:
    name: redis-replica