# The load balancer is expose to port 8000
# Label to load balancer is app
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
spec:
  type: "LoadBalancer"
  selector:
    app: app
  ports:
  - port: 8000
    targetPort: 8000
